#!/usr/bin/env bash
# This scripts install nginx on my web-01

sudo apt-get update && sudo apt-get -y upgrade

sudo apt-get -y install nginx

echo 'Hello World!' > index.html

sudo rm -r /var/www/html/index*.html

sudo mv index.html /var/www/html/

sudo service nginx start
