#!/usr/bin/env bash
# Custom HTTP RESPONSE HEADER

sudo apt-get update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.html

new_config="\ \n\tlocation \/redirect_me \{\ \n\t\treturn 301 \$scheme\:\/\/\$http_host\;\ \n\t\}\ \n"
sudo sed -i "/server_name _;/a $new_config" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/ww/html/404.html

new_404_config="\ \n\terror_page 404 \/404.html\;\ \n\tlocation = \/404.html \{\n\t\troot \/var\/www\/html\;\ \n\t\tinternal\;\n\t\}\ \n"
sudo sed -i "/server_name _;/a $new_404_config" /etc/nginx/sites-enabled/default

add_header="\ \n\tadd_header X-Served-By $HOSTNAME;\ \n"
sudo sed -i "/server_name _;/i $add_header" /etc/nginx/sites-enabled/default
sudo service nginx restart
