#!/usr/bin/env bash
# Install a load balancer

sudo apt-get update
sudo apt-get install haproxy -y

echo "ENABLED=1" | sudo tee /etc/default/haproxy

sudo mv /etc/haproxy/haproxy.cfg{,.original}

echo -e "frontend main\n\tbind *:80\n\tmode http\n\tdefault_backend servers\nbackend servers\n\tbalance roundrobin\n\tserver 87013-web-01 100.25.158.189:80 check\n\tserver 87013-web-02 54.236.45.59:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
