#!/usr/bin/env bash
# Install a load balancer

sudo apt-get update
sudo apt-get install haproxy -y

echo "ENABLED=1" | sudo tee /etc/default/haproxy

echo -e "frontend main\n\tbind *:80\n\tmode http\n\tdefault_backend servers\nbackend servers\n\tbalance roundrobin\n\tserver 87013-web-01 18.233.67.42:80 check\n\tserver 87013-web-02 54.237.66.155:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
