#!/usr/bin/env bash
# This script loops from 1 to 10 and displays
# "bad luck" for the 4th loop iteration
# "good luck" for the 8th loop iteration
# "Best School" for the other iterations

best_school="Best School"
bad_luck="bad luck"
good_luck="good luck"
i=1

while [ "$i" -le 10 ]
do
	if [ "$i" -eq 4 ]
	then
		echo "$bad_luck"
	elif [ "$i" -eq 8 ]
	then
		echo "$good_luck"
	else
		echo "$best_school"
	fi

	(( i++ ))
done
