#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and displays
# 4 and then "bad luck from China" for the 4th loop iteration
# 9 and then "bad luck from Japan" for the 9th loop iteration
# 17 and then "bad luck from Italy" for the 17th loop iteration

bad_luck="bad luck from"
i=1

while [ "$i" -le 20 ]
do
	echo "$i"
	case "$i" in 
		4)
			echo "$bad_luck" China
			;;
		9)
			echo "$bad_luck" Japan
			;;
		17)
			echo "$bad_luck" Italy
			;;
	esac
	(( i++ ))
done
