#!/usr/bin/env bash
# This script displays the content of the current directory
#+in a list format, where only the part of the name after the
#+first dash is displayed
# shellcheck disable=SC2012
for file in $(ls -A | cut --complement -d "-" -f 1)
do
	echo "$file"
done
