#!/usr/bin/env bash
# This script configures an Ubuntu server with the below requirement
# "localhost" resolves to 127.0.0.2
# "facebook.com" resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '/^127.0.0.*$/ a \8.8.8.8	facebook.com' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
